### ISSUE TITLE
Request to add puppeteer

### ISSUE THREAD

**Issue by rtargaryen** [posconnetwork/JS-Data-Retrieval-Sample#6]
Hi.

I am working on the Indian FIRs and using [acdm.in](http://www.acdm.in/ShowStations.php?q=vabb) (Suggested by Divya Patel) for ATIS information but the website requires account for accessing the data so I have used a headless browser package for js named [puppeteer](https://www.npmjs.com/package/puppeteer) for automatically filling the creds and fetching data.

Therefore I request you to add puppeteer to the allowed packages list.

**Comment by space55** [comment]
I'll add it to the allowed modules listing

**Comment by space55** [comment]
I just took a look into getting the system working w/ Puppeteer, and I don't think it will work for us in production. The servers it will run on don't have a UI, they are terminal-only, so I'm not sure that Chrome will work too well. In addition, I'm not super comfortable exposing a Chrome instance, for security reasons. Would it be possible to use another library, like Axios, to achieve the desired results?

In addition, with the specific implementation you provided, it takes upwards of two minutes to get a reply for ATIS. I understand it's not your fault, it's a slow remote server, but we can't really wait that long for a response. The timeout is currently set to ten seconds.

**Comment by wegylexy** [comment]
It is actually pretty straight forward.
1. Login
   ```
   POST /index.php
   Host: www.acdm.in
   
   username={username}&submit=Submit&password={password}
   ```
2. Use the `PHPSESSID` cookie for each station
   ```
   GET /ShowStations.php?q={icao}
   Host: www.acdm.in
   Cookie: PHPSESSID={phpSessionId}
   ```
3. Parse the HTML
   ```js
   document.querySelector("td + td").textContent; // select the next sibling <td> after the first <td>
   ```

**Comment by wegylexy** [comment]
See https://flaviocopes.com/axios-credentials/ for how to use cookies with `axios`

**Comment by rtargaryen** [comment]
Noted @space55.
Thanks @wegylexy will check that.

**Comment by wegylexy** [comment]
Sample for VABF added in https://github.com/posconnetwork/JS-Data-Retrieval-Sample/commit/9bed42cd8f99f53fa01e0e7b0005a4a07aeb10a9#diff-1b8e123fe433172658a372e71521b2ce
